export const comicCodes = [
  { label: '1-and-Done', value: '1-and-done' },
  { label: '9 Chickweed Lane', value: '9-chickweed-lane' },
  { label: '9 to 5', value: '9to5' },
  { label: 'A Problem Like Jamal', value: 'a-problem-like-jamal' },
  { label: 'Aaggghhh', value: 'aaggghhh' },
  { label: 'Adam at Home', value: 'adamathome' },
  { label: 'Adult Children', value: 'adult-children' },
  { label: 'Agnes', value: 'agnes' },
  { label: 'AJ and Magnus', value: 'aj-and-magnus' },
  { label: 'Ali\'s House', value: 'alis-house' },
  { label: 'Alley Oop', value: 'alley-oop' },
  { label: 'Amanda the Great', value: 'amanda-the-great' },
  { label: 'Andertoons', value: 'andertoons' },
  { label: 'Andy Capp', value: 'andycapp' },
  { label: 'Angry Little Girls', value: 'angry-little-girls' },
  { label: 'Animal Crackers', value: 'animalcrackers' },
  { label: 'Annie', value: 'annie' },
  { label: 'Arlo and Janis', value: 'arloandjanis' },
  { label: 'Art by Moga', value: 'artbymoga' },
  { label: 'Ask Shagg', value: 'askshagg' },
  { label: 'Aunty Acid', value: 'aunty-acid' },
  { label: 'Baby Blues', value: 'babyblues' },
  { label: 'Back to B.C.', value: 'back-to-bc' },
  { label: 'Back in the Day', value: 'backintheday' },
  { label: 'Bacon', value: 'bacon' },
  { label: 'Bad Machinery', value: 'bad-machinery' },
  { label: 'Baldo', value: 'baldo' },
  { label: 'Ballard Street', value: 'ballardstreet' },
  { label: 'Banana Triangle', value: 'banana-triangle' },
  { label: 'Barkeater Lake', value: 'barkeaterlake' },
  { label: 'Barney and Clyde', value: 'barneyandclyde' },
  { label: 'Basic Instructions', value: 'basicinstructions' },
  { label: 'Batch Rejection', value: 'batch-rejection' },
  { label: 'BC', value: 'bc' },
  { label: 'Beardo', value: 'beardo' },
  { label: 'Ben', value: 'ben' },
  { label: 'Berger and Wyse', value: 'berger-and-wyse' },
  { label: 'Berkeley Mews', value: 'berkeley-mews' },
  { label: 'Betty', value: 'betty' },
  { label: 'BFGF Syndrome', value: 'bfgf-syndrome' },
  { label: 'Big Nate', value: 'bignate' },
  { label: 'Big Top', value: 'bigtop' },
  { label: 'Bird and Moon', value: 'bird-and-moon' },
  { label: 'Birdbrains', value: 'birdbrains' },
  { label: 'Bleeker', value: 'bleeker' },
  { label: 'Bliss', value: 'bliss' },
  { label: 'Bloom County', value: 'bloom-county' },
  { label: 'Bloom County', value: 'bloomcounty' },
  { label: 'Bob the Angry Flower', value: 'bob-the-angry-flower' },
  { label: 'Bob the Squirrel', value: 'bobthesquirrel' },
  { label: 'Bonanas', value: 'bonanas' },
  { label: 'Boomerangs', value: 'boomerangs' },
  { label: 'The Boondocks', value: 'boondocks' },
  { label: 'Bottom Liners', value: 'bottomliners' },
  { label: 'Bound and Gagged', value: 'boundandgagged' },
  { label: 'Bozo', value: 'bozo' },
  { label: 'Breaking Cat News', value: 'breaking-cat-news' },
  { label: 'Brevity', value: 'brevity' },
  { label: 'Brewster Rockit', value: 'brewsterrockit' },
  { label: 'Broom-Hilda', value: 'broomhilda' },
  { label: 'Buckles', value: 'buckles' },
  { label: 'Bully', value: 'bully' },
  { label: 'Buni', value: 'buni' },
  { label: 'Calvin and Hobbes', value: 'calvinandhobbes' },
  { label: 'Cathy', value: 'cathy' },
  { label: 'Cathy Commiserations', value: 'cathy-commiserations' },
  { label: 'Cats Cafe', value: 'cats-cafe' },
  { label: 'Cattitude Doggonit', value: 'cattitude-doggonit' },
  { label: 'Cest la Vie', value: 'cestlavie' },
  { label: 'Cheer Up Emo Kid', value: 'cheer-up-emo-kid' },
  { label: 'Chuck Draws Things', value: 'chuckdrawsthings' },
  { label: 'Chucklebros', value: 'chucklebros' },
  { label: 'Citizen Dog', value: 'citizendog' },
  { label: 'Claw', value: 'claw' },
  { label: 'Cleats', value: 'cleats' },
  { label: 'Close to Home', value: 'closetohome' },
  { label: 'Compu-Toon', value: 'compu-toon' },
  { label: 'Cornered', value: 'cornered' },
  { label: 'Cow and Boy', value: 'cowandboy' },
  { label: 'Cow Town', value: 'cowtown' },
  { label: 'Crabgrass', value: 'crabgrass' },
  { label: 'Crankshaft', value: 'crankshaft' },
  { label: 'Crumb', value: 'crumb' },
  { label: 'Cul de Sac', value: 'culdesac' },
  { label: 'Curses', value: 'curses' },
  { label: 'Daddy\'s Home', value: 'daddyshome' },
  { label: 'Dark Side of the Horse', value: 'darksideofthehorse' },
  { label: 'Day by Dave', value: 'day-by-dave' },
  { label: 'Deep Dark Fears', value: 'deep-dark-fears' },
  { label: 'DeFlocked', value: 'deflocked' },
  { label: 'Diamond Lil', value: 'diamondlil' },
  { label: 'Dick Tracy', value: 'dicktracy' },
  { label: 'The Dinette Set', value: 'dinetteset' },
  { label: 'Dinosaur Comics', value: 'dinosaur-comics' },
  { label: 'Dog Eat Doug', value: 'dogeatdoug' },
  { label: 'Dogs of C-Kennel', value: 'dogsofckennel' },
  { label: 'Domestic Abuse', value: 'domesticabuse' },
  { label: 'Don Brutus', value: 'don-brutus' },
  { label: 'Doodle for Food', value: 'doodle-for-food' },
  { label: 'Doodle Town', value: 'doodle-town' },
  { label: 'Doonesbury', value: 'doonesbury' },
  { label: 'Drabble', value: 'drabble' },
  { label: 'Drew Litton', value: 'drewlitton' },
  { label: 'The Duplex', value: 'duplex' },
  { label: 'Edge City', value: 'edge-city' },
  { label: 'Eek', value: 'eek' },
  { label: 'Emmy Lou', value: 'emmy-lou' },
  { label: 'Endtown', value: 'endtown' },
  { label: 'Everyday People Cartoons', value: 'everyday-people-cartoons' },
  { label: 'Eyebeam', value: 'eyebeam' },
  { label: 'False Knees', value: 'false-knees' },
  { label: 'The Family Tree', value: 'familytree' },
  { label: 'Farcus', value: 'farcus' },
  { label: 'Fat Cats', value: 'fat-cats' },
  { label: 'Flo and Friends', value: 'floandfriends' },
  { label: 'F Minus', value: 'fminus' },
  { label: 'Foolish Mortals', value: 'foolish-mortals' },
  { label: 'For Better or For Worse', value: 'forbetterorforworse' },
  { label: 'For Heaven\'s Sake', value: 'forheavenssake' },
  { label: 'Four Eyes', value: 'four-eyes' },
  { label: 'Fowl Language', value: 'fowl-language' },
  { label: 'FoxTrot', value: 'foxtrot' },
  { label: 'FoxTrot Classics', value: 'foxtrotclassics' },
  { label: 'Francis', value: 'francis' },
  { label: 'Frank and Ernest', value: 'frank-and-ernest' },
  { label: 'Frazz', value: 'frazz' },
  { label: 'Fred Basset', value: 'fredbasset' },
  { label: 'Free Range', value: 'freerange' },
  { label: 'Freshly Squeezed', value: 'freshlysqueezed' },
  { label: 'Frog Applause', value: 'frogapplause' },
  { label: 'Funky Winkerbean', value: 'funky-winkerbean' },
  { label: 'Furbabies', value: 'furbabies' },
  { label: 'G-Man Webcomics', value: 'g-man-webcomics' },
  { label: 'Garfield', value: 'garfield' },
  { label: 'Gasoline Alley', value: 'gasolinealley' },
  { label: 'Geech', value: 'geech' },
  { label: 'Get a Life', value: 'getalife' },
  { label: 'Get Fuzzy', value: 'getfuzzy' },
  { label: 'Gil', value: 'gil' },
  { label: 'Gil Thorp', value: 'gilthorp' },
  { label: 'Ginger Meggs', value: 'gingermeggs' },
  { label: 'Glasbergen Cartoons', value: 'glasbergen-cartoons' },
  { label: 'Globetrotter', value: 'globetrotter' },
  { label: 'Goats', value: 'goats' },
  { label: 'Grand Avenue', value: 'grand-avenue' },
  { label: 'Gray Matters', value: 'gray-matters' },
  { label: 'Green Humour', value: 'green-humour' },
  { label: 'Haircut Practice', value: 'haircut-practice' },
  { label: 'Half Full', value: 'half-full' },
  { label: 'Harley', value: 'harley' },
  { label: 'Heart of the City', value: 'heartofthecity' },
  { label: 'Heathcliff', value: 'heathcliff' },
  { label: 'Herb and Jamaal', value: 'herbandjamaal' },
  { label: 'Herman', value: 'herman' },
  { label: 'Home and Away', value: 'homeandaway' },
  { label: 'Home Free', value: 'homefree' },
  { label: 'Hot Comics for Cool People', value: 'hot-comics-for-cool-people' },
  { label: 'The Humble Stumble', value: 'humble-stumble' },
  { label: 'Hutch Owen', value: 'hutch-owen' },
  { label: 'Imagine This', value: 'imaginethis' },
  { label: 'Imogen Quest', value: 'imogen-quest' },
  { label: 'In Security', value: 'in-security' },
  { label: 'Ink Pen', value: 'inkpen' },
  { label: 'In the Bleachers', value: 'inthebleachers' },
  { label: 'In the Sticks', value: 'inthesticks' },
  { label: 'Invisible Bread', value: 'invisible-bread' },
  { label: 'It\'s All About You', value: 'itsallaboutyou' },
  { label: 'Jake Likes Onions', value: 'jake-likes-onions' },
  { label: 'Jane\'s World', value: 'janesworld' },
  { label: 'Jerry King Comics', value: 'jerry-king-comics' },
  { label: 'Jim Benton Cartoons', value: 'jim-benton-cartoons' },
  { label: 'JumpStart', value: 'jumpstart' },
  { label: 'Junk Drawer', value: 'junk-drawer' },
  { label: 'Kid Beowulf', value: 'kid-beowulf' },
  { label: 'Kitchen Capers', value: 'kitchen-capers' },
  { label: 'B. Kliban', value: 'kliban' },
  { label: 'Kliban\'s Cats', value: 'klibans-cats' },
  { label: 'La Cucaracha', value: 'lacucaracha' },
  { label: 'Lard\'s World Peace Tips', value: 'lards-world-peace-tips' },
  { label: 'Last Kiss', value: 'lastkiss' },
  { label: 'Laughing Redhead Comics', value: 'laughing-redhead-comics' },
  { label: 'Lay Lines', value: 'lay-lines' },
  { label: 'Learn to Speak Cat', value: 'learn-to-speak-cat' },
  { label: 'Liberty Meadows', value: 'libertymeadows' },
  { label: 'Life on Earth', value: 'life-on-earth' },
  { label: 'Li\'l Abner', value: 'lil-abner' },
  { label: 'Lio', value: 'lio' },
  { label: 'Little Fried Chicken and Sushi', value: 'little-fried-chicken-and-sushi' },
  { label: 'Little Moments of Love', value: 'little-moments-of-love' },
  { label: 'Little Nemo', value: 'little-nemo' },
  { label: 'Little Dog Lost', value: 'littledoglost' },
  { label: 'Liz Climo Cartoons', value: 'liz-climo-cartoons' },
  { label: 'The Lockhorns', value: 'lockhorns' },
  { label: 'Lola', value: 'lola' },
  { label: 'Long Story Short', value: 'long-story-short' },
  { label: 'Looks Good on Paper', value: 'looks-good-on-paper' },
  { label: 'Loose Parts', value: 'looseparts' },
  { label: 'Lost Sheep', value: 'lostsheep' },
  { label: 'Luann', value: 'luann' },
  { label: 'Luann Againn', value: 'luann-againn' },
  { label: 'Lucky Cow', value: 'luckycow' },
  { label: 'Lug Nuts', value: 'lug-nuts' },
  { label: 'Lunarbaboon', value: 'lunarbaboon' },
  { label: 'Maintaining', value: 'maintaining' },
  { label: 'Mannequin on the Moon', value: 'mannequin-on-the-moon' },
  { label: 'Maria\'s Day', value: 'marias-day' },
  { label: 'Marmaduke', value: 'marmaduke' },
  { label: 'The Meaning of Lila', value: 'meaningoflila' },
  { label: 'Medium Large', value: 'medium-large' },
  { label: 'Messy Cow', value: 'messy-cow' },
  { label: 'Mexikid Stories', value: 'mexikid-stories' },
  { label: 'Mike du Jour', value: 'mike-du-jour' },
  { label: 'Miss Peach', value: 'miss-peach' },
  { label: 'Moderately Confused', value: 'moderately-confused' },
  { label: 'Molly and the Bear', value: 'molly-and-the-bear' },
  { label: 'Momma', value: 'momma' },
  { label: 'Monty', value: 'monty' },
  { label: 'Mother Goose and Grimm', value: 'mother-goose-and-grimm' },
  { label: 'Motley Classics', value: 'motley-classics' },
  { label: 'Mr. Lowe', value: 'mr-lowe' },
  { label: 'Mutt and Jeff', value: 'muttandjeff' },
  { label: 'My Dad Is Dracula', value: 'my-dad-is-dracula' },
  { label: 'Mythtickle', value: 'mythtickle' },
  { label: 'Nancy', value: 'nancy' },
  { label: 'Nancy Classics', value: 'nancy-classics' },
  { label: 'Nest Heads', value: 'nestheads' },
  { label: 'Neurotica', value: 'neurotica' },
  { label: 'Next Door Neighbors', value: 'next-door-neighbors' },
  { label: 'Nick and Zuzu', value: 'nick-and-zuzu' },
  { label: 'Non Sequitur', value: 'nonsequitur' },
  { label: 'Not Invented Here', value: 'not-invented-here' },
  { label: 'Nothing is Not Something', value: 'nothing-is-not-something' },
  { label: 'Now Recharging', value: 'now-recharging' },
  { label: 'Off the Mark', value: 'offthemark' },
  { label: 'Oh, Brother!', value: 'oh-brother' },
  { label: 'Ollie and Quentin', value: 'ollie-and-quentin' },
  { label: 'On a Claire Day', value: 'onaclaireday' },
  { label: 'One Big Happy', value: 'onebighappy' },
  { label: 'Ordinary Bill', value: 'ordinary-bill' },
  { label: 'Origins of the Sunday Comics', value: 'origins-of-the-sunday-comics' },
  { label: 'Our Super Adventure', value: 'our-super-adventure' },
  { label: 'Outland', value: 'outland' },
  { label: 'Out of the Gene Pool', value: 'outofthegenepool' },
  { label: 'Overboard', value: 'overboard' },
  { label: 'Over the Hedge', value: 'overthehedge' },
  { label: 'Ozy and Millie', value: 'ozy-and-millie' },
  { label: 'Peanuts', value: 'peanuts' },
  { label: 'Peanuts Begins', value: 'peanuts-begins' },
  { label: 'Pearls Before Swine', value: 'pearlsbeforeswine' },
  { label: 'The Perry Bible Fellowship', value: 'perry-bible-fellowship' },
  { label: 'Phoebe and Her Unicorn', value: 'phoebe-and-her-unicorn' },
  { label: 'Pibgorn', value: 'pibgorn' },
  { label: 'Pibgorn Sketches', value: 'pibgornsketches' },
  { label: 'Pickles', value: 'pickles' },
  { label: 'Please Listen to Me', value: 'please-listen-to-me' },
  { label: 'Pluggers', value: 'pluggers' },
  { label: 'Pooch Cafe', value: 'poochcafe' },
  { label: 'Poorcraft', value: 'poorcraft' },
  { label: 'Poorly Drawn Lines', value: 'poorly-drawn-lines' },
  { label: 'Pot-Shots', value: 'pot-shots' },
  { label: 'PreTeena', value: 'preteena' },
  { label: 'Prickly City', value: 'pricklycity' },
  { label: 'Questionable Quotebook', value: 'questionable-quotebook' },
  { label: 'Rabbits Against Magic', value: 'rabbitsagainstmagic' },
  { label: 'Raising Duncan', value: 'raising-duncan' },
  { label: 'Randolph Itch', value: 'randolphitch' },
  { label: 'Reality Check', value: 'realitycheck' },
  { label: 'Real Life Adventures', value: 'reallifeadventures' },
  { label: 'Red and Rover', value: 'redandrover' },
  { label: 'Red Meat', value: 'redmeat' },
  { label: 'Richard\'s Poor Almanac', value: 'richards-poor-almanac' },
  { label: 'Rip Haywire', value: 'riphaywire' },
  { label: 'Ripley\'s Believe It or Not!', value: 'ripleysbelieveitornot' },
  { label: 'Robbie and Bobby', value: 'robbie-and-bobby' },
  { label: 'Rose is Rose', value: 'roseisrose' },
  { label: 'Rubes', value: 'rubes' },
  { label: 'Sarah\'s Scribbles', value: 'sarahs-scribbles' },
  { label: 'Saturday Morning Breakfast Cereal', value: 'saturday-morning-breakfast-cereal' },
  { label: 'Savage Chickens', value: 'savage-chickens' },
  { label: 'Scary Gary', value: 'scarygary' },
  { label: 'Scenes From A Multiverse', value: 'scenes-from-a-multiverse' },
  { label: 'Shen Comix', value: 'shen-comix' },
  { label: 'Sherman\'s Lagoon', value: 'shermanslagoon' },
  { label: 'Shirley and Son Classics', value: 'shirley-and-son-classics' },
  { label: 'Shoe', value: 'shoe' },
  { label: 'Sketch Shark Comics', value: 'sketchshark-comics' },
  { label: 'Skin Horse', value: 'skinhorse' },
  { label: 'Skippy', value: 'skippy' },
  { label: 'Small Potatoes', value: 'small-potatoes' },
  { label: 'Snow Sez', value: 'snow-sez' },
  { label: 'Speed Bump', value: 'speedbump' },
  { label: 'Spirit of the Staircase', value: 'spirit-of-the-staircase' },
  { label: 'Spot the Frog', value: 'spot-the-frog' },
  { label: 'Sticky Comics', value: 'sticky-comics' },
  { label: 'Stone Soup', value: 'stonesoup' },
  { label: 'Strange Brew', value: 'strangebrew' },
  { label: 'Studio Jantze', value: 'studio-jantze' },
  { label: 'Sunny Street', value: 'sunny-street' },
  { label: 'Super-Fun-Pak Comix', value: 'super-fun-pak-comix' },
  { label: 'The Swan Eaters', value: 'swan-eaters' },
  { label: 'Sweet & Sour Pork', value: 'sweet-and-sour-pork' },
  { label: 'Sylvia', value: 'sylvia' },
  { label: 'Tank McNamara', value: 'tankmcnamara' },
  { label: 'Tarzan', value: 'tarzan' },
  { label: 'Tavi Cat', value: 'tavicat' },
  { label: 'Ten Cats', value: 'ten-cats' },
  { label: 'Tex', value: 'tex' },
  { label: 'Texts from Mittens', value: 'texts-from-mittens' },
  { label: 'That is Priceless', value: 'that-is-priceless' },
  { label: 'That New Carl Smell', value: 'that-new-carl-smell' },
  { label: 'Thatababy', value: 'thatababy' },
  { label: 'The Academia Waltz', value: 'the-academia-waltz' },
  { label: 'The Adventures of Business Cat', value: 'the-adventures-of-business-cat' },
  { label: 'The Awkward Yeti', value: 'the-awkward-yeti' },
  { label: 'The Born Loser', value: 'the-born-loser' },
  { label: 'The Comic Strip That Has a Finale Every Day', value: 'the-comic-strip-that-has-a-finale-every-day' },
  { label: 'The Daily Drawing', value: 'the-daily-drawing' },
  { label: 'The Martian Confederacy', value: 'the-martian-confederacy' },
  { label: 'The Middle Age', value: 'the-middle-age' },
  { label: 'The Wandering Melon', value: 'the-wandering-melon' },
  { label: 'The Worried Well', value: 'the-worried-well' },
  { label: 'The Argyle Sweater', value: 'theargylesweater' },
  { label: 'The Barn', value: 'thebarn' },
  { label: 'The Big Picture', value: 'thebigpicture' },
  { label: 'The Buckets', value: 'thebuckets' },
  { label: 'The City', value: 'thecity' },
  { label: 'The Doozies', value: 'thedoozies' },
  { label: 'The Elderberries', value: 'theelderberries' },
  { label: 'The Flying McCoys', value: 'theflyingmccoys' },
  { label: 'The Fusco Brothers', value: 'thefuscobrothers' },
  { label: 'The Grizzwells', value: 'thegrizzwells' },
  { label: 'The K Chronicles', value: 'thekchronicles' },
  { label: 'The Knight Life', value: 'theknightlife' },
  { label: 'The Middletons', value: 'themiddletons' },
  { label: 'The New Adventures of Queen Victoria', value: 'thenewadventuresofqueenvictoria' },
  { label: 'The Norm', value: 'thenorm' },
  { label: 'The Other Coast', value: 'theothercoast' },
  { label: 'Thin Lines', value: 'thinlines' },
  { label: 'Tiny Sepuku', value: 'tinysepuku' },
  { label: 'Today\'s Szep', value: 'todays-szep' },
  { label: 'Tom the Dancing Bug', value: 'tomthedancingbug' },
  { label: 'Too Much Coffee Man', value: 'toomuchcoffeeman' },
  { label: 'UFO', value: 'ufo' },
  { label: 'Underpants and Overbites', value: 'underpants-and-overbites' },
  { label: 'Understanding Chaos', value: 'understanding-chaos' },
  { label: 'Unstrange Phenomena', value: 'unstrange-phenomena' },
  { label: 'The Upside-Down World of Gustave Verbeek', value: 'upside-down-world-of-gustave-verbeek' },
  { label: 'Wallace the Brave', value: 'wallace-the-brave' },
  { label: 'Warped', value: 'warped' },
  { label: 'Watch Your Head', value: 'watchyourhead' },
  { label: 'Wawawiwa', value: 'wawawiwa' },
  { label: 'WaynoVision', value: 'waynovision' },
  { label: 'Wee Pals', value: 'weepals' },
  { label: 'Widdershins', value: 'widdershins' },
  { label: 'Wide Open', value: 'wide-open' },
  { label: 'Wizard of Id Classics', value: 'wizard-of-id-classics' },
  { label: 'Wizard of Id', value: 'wizardofid' },
  { label: 'Wondermark', value: 'wondermark' },
  { label: 'Working Daze', value: 'working-daze' },
  { label: 'Working It Out', value: 'workingitout' },
  { label: 'Worry Lines', value: 'worry-lines' },
  { label: 'Wrong Hands', value: 'wrong-hands' },
  { label: 'W.T. Duck', value: 'wtduck' },
  { label: 'Wumo', value: 'wumo' },
  { label: 'Yaffle', value: 'yaffle' },
  { label: 'Yeah, It\'s Chill', value: 'yeah-its-chill' },
  { label: 'Yes, I\'m Hot in This', value: 'yesimhotinthis' },
  { label: 'Zack Hill', value: 'zackhill' },
  { label: 'Zen Pencils', value: 'zen-pencils' },
  { label: 'Ziggy', value: 'ziggy' },
];